// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcUAeVdCeu3Wa_aIZ9as9pyTks5h2wik',
    appId: '1:144930929084:web:84c2fc0421b3375f23d3b9',
    messagingSenderId: '144930929084',
    projectId: 'tufecrecelibros',
    authDomain: 'tufecrecelibros.firebaseapp.com',
    storageBucket: 'tufecrecelibros.firebasestorage.app',
    measurementId: 'G-HVFT74SC2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe0Lq4FfFjRFCFSXNbZA0QS4nFsZ6An6I',
    appId: '1:144930929084:android:845543396059638e23d3b9',
    messagingSenderId: '144930929084',
    projectId: 'tufecrecelibros',
    storageBucket: 'tufecrecelibros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5e2lB8QfPiREWIsaQ4wgyTVgiB1-fUg',
    appId: '1:144930929084:ios:a38effe5ea426aea23d3b9',
    messagingSenderId: '144930929084',
    projectId: 'tufecrecelibros',
    storageBucket: 'tufecrecelibros.firebasestorage.app',
    iosClientId: '144930929084-chfk8rq8291166dnei8i65u8avci4i56.apps.googleusercontent.com',
    iosBundleId: 'com.example.deglorialibros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF5e2lB8QfPiREWIsaQ4wgyTVgiB1-fUg',
    appId: '1:144930929084:ios:a38effe5ea426aea23d3b9',
    messagingSenderId: '144930929084',
    projectId: 'tufecrecelibros',
    storageBucket: 'tufecrecelibros.firebasestorage.app',
    iosClientId: '144930929084-chfk8rq8291166dnei8i65u8avci4i56.apps.googleusercontent.com',
    iosBundleId: 'com.example.deglorialibros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLcUAeVdCeu3Wa_aIZ9as9pyTks5h2wik',
    appId: '1:144930929084:web:e855534e3a598df123d3b9',
    messagingSenderId: '144930929084',
    projectId: 'tufecrecelibros',
    authDomain: 'tufecrecelibros.firebaseapp.com',
    storageBucket: 'tufecrecelibros.firebasestorage.app',
    measurementId: 'G-36KSXHDEQW',
  );
}
