#!/bin/bash
# Script para verificar y recrear variables de entorno en Vercel

echo "🔍 Verificando variables de entorno en Vercel..."
echo ""

# Valores correctos desde firebase_options.dart
API_KEY="AIzaSyDLcUAeVdCeu3Wa_aIZ9as9pyTks5h2wik"
AUTH_DOMAIN="tufecrecelibros.firebaseapp.com"
PROJECT_ID="tufecrecelibros"
STORAGE_BUCKET="tufecrecelibros.firebasestorage.app"
MESSAGING_SENDER_ID="144930929084"
APP_ID="1:144930929084:web:84c2fc0421b3375f23d3b9"
MEASUREMENT_ID="G-HVFT74SC2T"

echo "📋 Variables requeridas:"
echo "  NEXT_PUBLIC_FIREBASE_API_KEY=$API_KEY"
echo "  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN"
echo "  NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID"
echo "  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET"
echo "  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID"
echo "  NEXT_PUBLIC_FIREBASE_APP_ID=$APP_ID"
echo "  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$MEASUREMENT_ID"
echo ""
echo "⚠️  Para eliminar y recrear variables, ejecuta estos comandos:"
echo ""
echo "# Eliminar variables existentes (si es necesario)"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_API_KEY production preview development"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production preview development"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_PROJECT_ID production preview development"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET production preview development"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID production preview development"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_APP_ID production preview development"
echo "vercel env rm NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID production preview development"
echo ""
echo "# Agregar variables con valores correctos"
echo "echo '$API_KEY' | vercel env add NEXT_PUBLIC_FIREBASE_API_KEY production preview development"
echo "echo '$AUTH_DOMAIN' | vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production preview development"
echo "echo '$PROJECT_ID' | vercel env add NEXT_PUBLIC_FIREBASE_PROJECT_ID production preview development"
echo "echo '$STORAGE_BUCKET' | vercel env add NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET production preview development"
echo "echo '$MESSAGING_SENDER_ID' | vercel env add NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID production preview development"
echo "echo '$APP_ID' | vercel env add NEXT_PUBLIC_FIREBASE_APP_ID production preview development"
echo "echo '$MEASUREMENT_ID' | vercel env add NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID production preview development"

